name: Test Code On Push

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check Repo code
              uses: actions/checkout@v3
            - name: Test code
              run: docker build -t lerolero-test . && docker run -it --rm lerolero-test